### ISSUE TITLE
Node-Red (Local) 

### ISSUE THREAD

**Issue by EdLuz111** [YuriPierriV/racemap#20]

**Comment by YuriPierriV** [comment]
- [ ] Estudar possibilidade de fazer comunicação MQTT sem a necessidade do node-red diretamente com o broker:

https://www.youtube.com/watch?v=g48OIzaX4_s&t=2s

**Comment by YuriPierriV** [comment]
https://www.hivemq.com/blog/mqtt-client-library-mqtt-js/

https://www.hivemq.com/blog/mqtt-client-library-encyclopedia-arduino-pubsubclient/
