### ISSUE TITLE
Banco de dados (Local) 

### ISSUE THREAD

**Issue by EdLuz111** [YuriPierriV/racemap#7]
- [x] Qual usar?
- [x] Conectar com o servidor 
- [x] Criar endpoint `/status`
- [x] Subir banco de dados local
- [x] Criar modulo `databse.js` ou similar
- [x] Finalizar retorno do endpoint `/status`
- [x] Mover `.env` para development
- [x] Adicionar `jsconfig.json` com baseurl
- [x] Adicionar scripts dos serviços

**Comment by YuriPierriV** [comment]
https://node-postgres.com/
